### ISSUE TITLE
Issue on production server

### ISSUE THREAD

**Issue by cicciopage** [wangkanai/Responsive#23]
Hi,
I developed my mobile view on my development computer and everything is right. Tonight i tried to publish on production server and I get the following error:
NullReferenceException: Object reference not set to an instance of an object.
Wangkanai.Responsive.ResponsiveViewLocationExpander.PopulateValues(ViewLocationExpanderContext context)

what's the meaning?
Thanks,
Francesco.

**Comment by wangkanai** [comment]
Its got something to https://github.com/wangkanai/Detection/issues/76 the Responsive depend upon. When I publish Detection beta 10 and then i would publish this Responsive nuget as beta 5
